let booksArray = [
     ['5G81', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['52H96', '../../Assets/Images/Books/Light_Novel/dau_oi_bay_di.jpg', 'light novel', 'tragedy', 'đau ơi bay đi', 45, 120000],
     ['49B44', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['53F8', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['56R98', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['40T37', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['83D11', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['41Y21', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['96H88', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['81B81', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['10G58', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['83L62', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['8X91', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['54Q61', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['72U90', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['5U96', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['55D98', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['52I22', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['12I12', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['92R46', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['11S48', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['30Z70', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['57Q51', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['40P76', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['72X41', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['74Z14', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['24A73', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['52I5', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['41F12', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['40J80', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['100C61', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['93O64', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['77G96', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['75C78', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000],
     ['61H44', '../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg', 'light novel', 'tragedy', '3 ngày hạnh phúc', 31, 85000]
];

export default booksArray;