let booksArray = [
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy" , "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/dau_oi_bay_di.jpg", "light novel", "tragedy", "đau ơi bay đi", 45, 120000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000],
          ["../../Assets/Images/Books/Light_Novel/3_ngay_hanh_phuc.jpg", "light novel", "tragedy", "3 ngày hạnh phúc", 31, 85000]
]

export default booksArray;